const API="/api";
const state={role:"learner",section:"overview",projects:[{title:"Local Retail Content System",business:"Srinagar retail pilot",status:"In review",skill:"Content & Marketing"}],briefs:[],apiOnline:false};
const navs={learner:["overview","projects","passport","opportunities"],business:["overview","post brief","talent","projects"],admin:["overview","verification","pilot","analytics"]};
const titles={learner:"Learner Dashboard",business:"Business Workspace",admin:"Admin Console"};
async function api(path,options={}){const r=await fetch(API+path,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});if(!r.ok)throw new Error("API request failed");return r.status===204?{}:r.json()}
async function sync(){try{const h=await api("/health");state.apiOnline=!!h.ok;const b=await api("/briefs");state.briefs=b.items||[]}catch(e){state.apiOnline=false}}
function metric(a,b,c){return`<div class="card"><small>${a}</small><div class="big">${b}</div><small>${c}</small></div>`}
function nav(){document.querySelector("#sideNav").innerHTML=navs[state.role].map(x=>`<button class="${x===state.section?"active":""}" data-section="${x}">${x.replace(/\b\w/g,m=>m.toUpperCase())}</button>`).join("");document.querySelectorAll("#sideNav button").forEach(b=>b.onclick=()=>{state.section=b.dataset.section;render()})}
function esc(s=""){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function learner(){if(state.section==="projects")return`<div class="panel"><h2>Real Work Projects</h2>${state.projects.map(p=>`<div class="item"><div><b>${esc(p.title)}</b><div class="muted">${esc(p.business)} · ${esc(p.skill)}</div></div><span class="pill">${esc(p.status)}</span></div>`).join("")}</div>`;if(state.section==="passport")return`<div class="panel"><span class="eyebrow">VERIFIED TALENT PASSPORT</span><h2>Evidence profile</h2><div class="cards">${metric("Verified projects","04","Portfolio evidence")}${metric("Business feedback","4.8/5","Pilot example")}${metric("Skills","07","Mapped micro-skills")}${metric("Status","Ready","Opportunity signal")}</div><div class="item"><div><b>Local Retail Campaign</b><div class="muted">Brief → deliverable → business feedback → verification</div></div><button class="action" onclick="toast('Proof viewer opened in demo mode')">View proof</button></div></div>`;if(state.section==="opportunities")return`<div class="panel"><h2>Opportunities</h2>${state.briefs.map(b=>`<div class="item"><div><b>${esc(b.title)}</b><div class="muted">${esc(b.business)} · ${esc(b.skills)}</div></div><button class="action" onclick="applyBrief('${b.id}')">Apply</button></div>`).join("")||'<div class="empty">No live briefs yet.</div>'}</div>`;return`<div class="cards">${metric("Projects","04","2 active")}${metric("Proof","12","Evidence items")}${metric("Feedback","4.8/5","Pilot example")}${metric("Opportunities",String(state.briefs.length||6),"Matched examples")}</div><div class="grid"><div class="panel"><h2>Real Work Lab</h2><div class="item"><div><b>Complete your current brief</b><div class="muted">Local Retail Content System</div></div><span class="pill">72%</span></div><div class="item"><div><b>Next micro-skill</b><div class="muted">Performance reporting</div></div><button class="action" onclick="toast('Learning module opened in demo mode')">Open</button></div></div><div class="panel"><h2>AI workspace</h2><p class="muted">Generate a project plan, improve a brief, map skills or prepare feedback.</p><button class="action" onclick="ai('learner')">Ask KaamLab AI</button></div></div>`}
function business(){if(state.section==="post brief")return`<div class="panel"><h2>Create a business brief</h2><p class="muted">Publish a real business problem to the KaamLab backend.</p><div class="form"><input id="bt" placeholder="Problem title"><textarea id="bd" placeholder="Describe the problem, expected deliverable and constraints"></textarea><input id="bs" placeholder="Skills required (e.g. Canva, content, research)"><input id="bb" placeholder="Budget in INR (optional)"><button class="action" onclick="saveBrief()">Publish brief</button></div></div>`;if(state.section==="talent")return`<div class="panel"><h2>Project-ready talent</h2><div class="item"><div><b>Candidate A · Digital Marketing</b><div class="muted">4 verified projects · business feedback available</div></div><button class="action" onclick="toast('Talent Passport opened')">Review</button></div><div class="item"><div><b>Candidate B · Design</b><div class="muted">3 verified projects · portfolio evidence available</div></div><button class="action" onclick="toast('Talent Passport opened')">Review</button></div></div>`;if(state.section==="projects")return`<div class="panel"><h2>Business projects</h2><div class="item"><div><b>Local retail content system</b><div class="muted">Learner delivery · verification pending</div></div><span class="pill">In review</span></div></div>`;return`<div class="cards">${metric("Active briefs",String(state.briefs.length||5),"API-backed when online")}${metric("Matched talent","18","Illustrative")}${metric("Projects","11","In progress")}${metric("Conversions","03","Illustrative")}</div><div class="grid"><div class="panel"><h2>Business Problem Marketplace</h2>${state.briefs.map(b=>`<div class="item"><div><b>${esc(b.title)}</b><div class="muted">${esc(b.business)} · ${esc(b.skills)}</div></div><span class="pill">Open</span></div>`).join("")||'<div class="empty">Publish a brief to start.</div>'}</div><div class="panel"><h2>AI brief builder</h2><p class="muted">Structure scope, skills and success criteria.</p><button class="action" onclick="ai('business')">Generate with AI</button></div></div>`}
function admin(){return`<div class="cards">${metric("Learners","15","Pilot target")}${metric("Businesses","05","Pilot target")}${metric("Tracks","03","Pilot target")}${metric("API",state.apiOnline?"ONLINE":"DEMO","Backend status")}</div><div class="grid"><div class="panel"><h2>Verification queue</h2><div class="item"><div><b>Retail content project</b><div class="muted">Evidence uploaded · feedback pending</div></div><button class="action" onclick="toast('Verification marked for review')">Review</button></div><div class="item"><div><b>Catalogue design project</b><div class="muted">Evidence uploaded · ready for verification</div></div><button class="action" onclick="toast('Project verified in demo mode')">Verify</button></div></div><div class="panel"><h2>Pilot health</h2><p class="muted">10–12 week Srinagar-first pilot · 15 learners · 5 businesses · 3 tracks.</p><div class="item"><b>Recruitment</b><span class="pill">On track</span></div><div class="item"><b>First briefs</b><span class="pill">Active</span></div><div class="item"><b>Paid opportunity conversion</b><span class="pill">To validate</span></div></div></div>`}
function render(){nav();document.querySelector("#roleName").textContent=titles[state.role].replace("Dashboard","workspace");document.querySelector("#roleSub").textContent=state.role==="learner"?"Build proof. Find opportunities.":state.role==="business"?"Post problems. Discover talent.":"Verify. Measure. Improve.";document.querySelector("#pageTitle").textContent=titles[state.role];document.querySelector("#content").innerHTML=state.role==="learner"?learner():state.role==="business"?business():admin()}
async function saveBrief(){try{const b=await api("/briefs",{method:"POST",body:JSON.stringify({title:document.querySelector("#bt").value||"Untitled business problem",description:document.querySelector("#bd").value,skills:document.querySelector("#bs").value,budget:document.querySelector("#bb").value,business:"KaamLab pilot business"})});state.briefs.unshift(b);state.section="overview";toast("Brief published to backend");render()}catch(e){toast("Backend unavailable. Run node server.js first.")}}
async function applyBrief(id){try{await api("/applications",{method:"POST",body:JSON.stringify({briefId:id,learner:"Demo learner"})});toast("Application submitted")}catch(e){toast("Backend unavailable. Start the API and retry.")}}
function toast(s){const m=document.querySelector("#modal");m.innerHTML=`<div class="modalbox"><button class="close" onclick="m.classList.remove('open')">×</button><h2>KaamLab</h2><p>${esc(s)}</p><button class="action" onclick="m.classList.remove('open')">Continue</button></div>`;m.classList.add("open")}
async function ai(role){try{const d=await api("/ai",{method:"POST",body:JSON.stringify({role})});toast(d.output||"AI response received")}catch(e){toast("AI demo: structure objective, deliverables, micro-skills, constraints, deadline and success criteria.")}}
document.querySelectorAll(".role-switch button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".role-switch button").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.role=b.dataset.role;state.section="overview";render()});
document.querySelector("#aiBtn").onclick=()=>ai(state.role);
await sync();render();